[package]
name = "stream-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = { version = "0.3", features = ["tls"] }
futures = "0.3"
byteorder = "1.5.0"
xflv = "0.4.4"
bytesio = "0.3.4"
bytes = "1.10.1"
