[package]
name = "stream-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = { version = "0.3", features = ["tls"] }
futures = "0.3"
byteorder = "1.5.0"
